### ISSUE TITLE
no open issues found with the reminder label

### ISSUE THREAD

**Issue by Drallas** [agrc/reminder-action#119]
The action runs and has a /remind me tag in a comment, but nothing is found and no notifications!

What am i doing wrong? 

<img width="363" alt="Screenshot 2023-01-07 at 14 53 28" src="https://user-images.githubusercontent.com/24792888/211154239-bc3d8dae-b666-4a95-bab3-6e32c03e4fb1.png">

<img width="481" alt="Screenshot 2023-01-07 at 14 53 15" src="https://user-images.githubusercontent.com/24792888/211154237-2e1af30c-93c5-40ad-b520-14d8f6d94a16.png">

**Comment by stdavis** [comment]
Did you implement the companion action https://github.com/agrc/create-reminder-action?

**Comment by Drallas** [comment]
I did copy pasted from [readme file](https://github.com/agrc/create-reminder-action) but weirdly no colorcoding.

<img width="845" alt="Screenshot 2023-01-14 at 12 30 20" src="https://user-images.githubusercontent.com/24792888/212469849-82610bbd-4291-4660-96b2-3cdf3cd31d6a.png">

It doesn't show up as a action
<img width="642" alt="Screenshot 2023-01-14 at 12 30 38" src="https://user-images.githubusercontent.com/24792888/212469851-74290da7-a98c-4b8c-814f-2d5a1ad05621.png">

Even after i create a reminder
<img width="446" alt="Screenshot 2023-01-14 at 12 30 53" src="https://user-images.githubusercontent.com/24792888/212469855-26ba1a12-3513-4416-8896-f7e2a8274d48.png">

What am i missing?

**Comment by Drallas** [comment]
The action is running, recreated the 'create action' file. 

One more question, where are these reminders to go (GitHub notifications / elsewhere)?

**Comment by Drallas** [comment]
It seems not to pick up on /remind me comments on issues!

Do I only need to set :
/remind me to do something tomorrow
on the issue?

Or do I also need to set a reminder label on the issue manually?

**Comment by Drallas** [comment]
fixed it, reminders working now!
