### ISSUE TITLE
Reminder alerts to Slack channel?

### ISSUE THREAD

**Issue by jasonloewen** [agrc/reminder-action#172]
Is there a way to send the issue reminder alert to a Slack channel? My Slack channel is subscribed to the GH repo, and I get issue open/close notifications. However, the issue reminder alerts only go to my email inbox. Maybe I'm missing something simple? Thanks.

**Comment by steveoh** [comment]
does `/github subscribe owner/repo comments` help?

**Comment by stdavis** [comment]
Relevant docs: https://github.com/integrations/slack#:~:text=These%20are%20disabled%20by%20default%2C%20and%20can%20be%20enabled%20with%20the%20/github%20subscribe%20owner/repo%20%5Bfeature%5D%20command

**Comment by jasonloewen** [comment]
Thanks guys. I missed something simple. Works perfectly.
