### ISSUE TITLE
  HttpError: Resource not accessible by integration

### ISSUE THREAD

**Issue by LukasWallrich** [agrc/reminder-action#185]
Thanks for this very promising tool - but I currently don't manage to set it up. Could you help me to identify whats going wrong here?

https://github.com/forrtproject/forrtproject.github.io/actions/runs/9842531466/job/27171653749

![image](https://github.com/agrc/reminder-action/assets/60155545/f5473806-bd69-440f-9601-aebf75c7cfdd)

**Comment by steveoh** [comment]
That looks like the code that adds a label... Do you have an issue named `reminder`?

It appears we don't document this and it may be a bug on our part that we should try and add the label when it exists and pop a warning to create it if it doesn't.

```js
await octokit.rest.issues.addLabels({
    ...getIssueProps(context),
    labels: [LABEL],
  });
  core.endGroup();
```

**Comment by steveoh** [comment]
The issue here is that your workflow didn't have permission to edit a pull request. Our example only showed for issues. We've updated the docs and there should be a pr to fix your issue. Thanks for bringing this up!

**Comment by LukasWallrich** [comment]
Thank you very much! Super helpful.
