### ISSUE TITLE
How to delete a reminder?

### ISSUE THREAD

**Issue by msafi** [agrc/reminder-action#189]
Thanks for the useful Action.

One question: How do I delete a reminder?

**Comment by stdavis** [comment]
Great question. I believe that you would remove the hidden data that the create-reminder-action adds to the issue body. For example, you would remove the highlighted item below:

![image](https://github.com/user-attachments/assets/8fcc4ce8-85be-4113-ab3c-a38e85434697)

It would also be a good idea to remove the comments that triggered the reminder in the first place. Let me know if that works.

**Comment by msafi** [comment]
Thank you! The reminder was set for 2025 and now I deleted it :)
